# inference_config.yaml

model:
  model_name: "klue/roberta-base"
  pii_state_dir: ""  # 개인정보 모델 가중치 경로
  confid_state_dir: ""  # 기밀정보 모델 가중치 경로

test:
  is_pii: True  # 개인정보모델 학습이면 True, 기밀정보모델 학습이면 False
  test_name: "250908_01"  # "실험일자(YYMMDD)_실험순번(SS)" 
  batch_size: 64
  device: "cuda:0"  # "cpu" or "cuda:0" or "cuda:1"

data:
  data_dir: "/home/student1/Data/01관리부"  # 검증데이터가 들어있는 directory

label_mapping:
  pii_label_2_id:
    일반정보: 0
    준식별자: 1
    개인정보: 2
  confid_label_2_id:
    일반정보 : 0
    기밀정보 : 1

db:
  host: "127.0.0.1"
  port: "55432"
  dbname: "postgres"
  user: "student1"
  password: "onestone"